#include "c/IO.c"
#include "c/graphics.c"
#include "c/gdt.c"
#include "c/idt.c"
#include "c/interrupts.c"
#include "c/keyboard.c"
#include "c/utils.c"
#include "c/time.c"
#include "c/text.c"
#include "c/init.c"
#include "c/mem.c"
#include "c/malloc.c"
#include "c/disc.c"
#include "c/syscall.c"
#include "c/shell.c"
#include "c/load_prog.c"

//external includes
//#include "filesystem/source/ff.c"

#include "c/debug.c"
